version: '3'
services:
  ros2:
    image: ros2_ws:latest
    build: .
    container_name: ros2_container
    network_mode: "host"
    volumes:
      - ./ros2_ws:/ros2_ws
    environment:
      - ROS_DOMAIN_ID=10
      - ROS_IP=0.0.0.0
    stdin_open: true
    tty: true

